ABCSolutionsTest/Models/Register.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ABCSolutionsTest.Models
{
    public class Register
    {
    }
}

ABCSolutionsTest/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using ABCSolutionsTest.Models;
using ABCSolutionsTest.DAL;
using Microsoft.EntityFrameworkCore;
using ABCSolutionsTest.Helpers;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore.Infrastructure;
using StackExchange.Redis;

namespace ABCSolutionsTest.Controllers
{
    public class AdminController : Controller
    {

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
            ViewBag.CurrentUser = SessionExtension.GetCurrentUser(context.HttpContext.Session);
            ViewBag.IsAuthenticated = SessionExtension.IsAuthenticated(context.HttpContext.Session);
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (!(ViewBag.IsAuthenticated && ViewBag.CurrentUser.IsAdmin))
                return RedirectToAction("Error", "Home");

            return View();
        }

        [HttpGet]
        public IActionResult Users()
        {
            if (!(ViewBag.IsAuthenticated && ViewBag.CurrentUser.IsAdmin))
                return RedirectToAction("Error", "Home");

            List<User> users = new List<User>();

            using (ABCTestDBConext dbctx = new ABCTestDBConext())
            {
                foreach(User user in dbctx.Users)
                    users.Add(user);
            }

            return View(users);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User user)
        {
            ViewBag.ErrorMessage = null;
            ViewBag.SuccessMessage = null;

            if (ModelState.IsValid)
            {
                using (ABCTestDBConext dbctx = new ABCTestDBConext())
                {
                    try
                    {
                        dbctx.Users.Add(user);
                        dbctx.SaveChanges();
                        ViewBag.SuccessMessage = "Пользователь создан успешно!";
                    }
                    catch (Exception x)
                    {
                        if (dbctx.Users.Count(e => e.EMail == user.EMail) > 0)
                        {
                            ViewBag.ErrorMessage = "Такой EMail уже существует!";
                        }
                        else if (dbctx.Users.Count(e => e.Login == user.Login) > 0)
                        {
                            ViewBag.ErrorMessage = "Такой Login уже существует!";
                        }
                        else
                        {
                            ViewBag.ErrorMessage = x.Message;
                        }
                    }
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Ошибочный запрос!";
            }

            return View(user);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            User user;

            using (ABCTestDBConext dbctx = new ABCTestDBConext())
            {
                user = dbctx.Users.Find(id);
            }

            return View("Edit", user);
        }

        [HttpPost]
        public ActionResult Edit(User user)
        {
            ViewBag.ErrorMessage = null;

            if (ModelState.IsValid)
            {
                using (ABCTestDBConext dbctx = new ABCTestDBConext())
                {
                    try
                    {
                        var user1 = dbctx.Users.Find(user.Id);
                        user1.EMail = user.EMail;
                        user1.Login = user.Login;
                        user1.Name = user.Name;
                        user1.IsAdmin = user.IsAdmin;

                        dbctx.Users.Update(user1);
                        dbctx.SaveChanges();

                        var user2 = dbctx.Users.Find(user.Id);

                        return RedirectToAction("Users");
                    }
                    catch (Exception x)
                    {
                        ViewBag.ErrorMessage = x.Message;
                    }
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Ошибочный запрос!";
            }

            return View("Edit", user);
        }


        [HttpGet]
        public ActionResult EditPassword(int id)
        {
            User user;

            using (ABCTestDBConext dbctx = new ABCTestDBConext())
            {
                user = dbctx.Users.Find(id);
            }

            return View("EditPassword", user);
        }

        [HttpPost]
        public ActionResult EditPassword(User user)
        {
            ViewBag.ErrorMessage = null;

            if (ModelState.IsValid)
            {
                using (ABCTestDBConext dbctx = new ABCTestDBConext())
                {
                    try
                    {
                        var user1 = dbctx.Users.Find(user.Id);
                        user1.Password = user.Password;
                        dbctx.Users.Update(user1);
                        dbctx.SaveChanges();
                        return RedirectToAction("Users");
                    }
                    catch (Exception x)
                    {
                        ViewBag.ErrorMessage = x.Message;
                    }
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Ошибочный запрос!";
            }

            return View("EditPassword", user);
        }

        [HttpGet]
        public ActionResult DeleteUser(int id)
        {
            User user;

            using (ABCTestDBConext dbctx = new ABCTestDBConext())
            {
                user = dbctx.Users.Find(id);
                dbctx.Users.Remove(user);
                dbctx.SaveChanges();
            }

            return RedirectToAction("Users");
        }



    }
}

ABCSolutionsTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using ABCSolutionsTest.Models;
using ABCSolutionsTest.DAL;
using Microsoft.EntityFrameworkCore;
using ABCSolutionsTest.Helpers;
using Microsoft.AspNetCore.Mvc.Filters;

namespace ABCSolutionsTest.Controllers
{
    public class HomeController : Controller
    {

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
            ViewBag.CurrentUser = SessionExtension.GetCurrentUser(context.HttpContext.Session);
            ViewBag.IsAuthenticated = SessionExtension.IsAuthenticated(context.HttpContext.Session);
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Logout()
        {
            SessionExtension.SetCurrentUser(HttpContext.Session, null);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User user)
        {
            ViewBag.ErrorMessage = null;

            if (ModelState.IsValid)
            {
                using (ABCTestDBConext dbctx = new ABCTestDBConext())
                {
                    try
                    {
                        dbctx.Users.Add(user);
                        dbctx.SaveChanges();
                        SessionExtension.SetCurrentUser(HttpContext.Session, user);
                        return RedirectToAction("Index", user);

                    }
                    catch (DbUpdateException x)
                    {
                        if (dbctx.Users.Count(e => e.EMail == user.EMail) > 0)
                        {
                            ViewBag.ErrorMessage = "Такой EMail уже существует!";
                        }
                        else if (dbctx.Users.Count(e => e.Login == user.Login) > 0)
                        {
                            ViewBag.ErrorMessage = "Такой Login уже существует!";
                        }
                        else
                        {
                            ViewBag.ErrorMessage = x.Message;
                        }
                    }
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Ошибочный запрос!";
            }

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model)
        {
            ViewBag.ErrorMessage = null;

            if (ModelState.IsValid)
            {
                using (ABCTestDBConext dbctx = new ABCTestDBConext())
                {
                    User user = dbctx.Users.SingleOrDefault(user1 => user1.Login == model.Login);

                    if (user == null)
                    {
                        ViewBag.ErrorMessage = "Пользователь " + model.Login + " не найден!";
                    }
                    else
                    {
                        SessionExtension.SetCurrentUser(HttpContext.Session, user);
                        return RedirectToAction("Index", user);
                    }
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Ошибочный запрос!";
            }

            return View(model);
        }

    }
}

ABCSolutionsTest/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using ABCSolutionsTest.Models;
using ABCSolutionsTest.DAL;
using Microsoft.EntityFrameworkCore;
using ABCSolutionsTest.Helpers;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore.Infrastructure;
using StackExchange.Redis;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ABCSolutionsTest.Controllers
{
    public class UserController : Controller
    {
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
            ViewBag.CurrentUser = SessionExtension.GetCurrentUser(context.HttpContext.Session);
            ViewBag.IsAuthenticated = SessionExtension.IsAuthenticated(context.HttpContext.Session);
        }


        [HttpGet]
        public IActionResult CreateMessage()
        {
            Message message = new Message();
            message.Time = DateTime.Now;

            FillUsers();

            return View(message);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMessage(Message message)
        {
            ViewBag.ErrorMessage = null;
            ViewBag.SuccessMessage = null;

            if (ModelState.IsValid)
            {
                using (ABCTestDBConext dbctx = new ABCTestDBConext())
                {
                    try
                    {
                        message.Time = DateTime.Now;
                        message.AuthorID = ViewBag.CurrentUser.Id;
                        dbctx.Messages.Add(message);
                        dbctx.SaveChanges();
                        ViewBag.SuccessMessage = "Сообщение успешно отправлено!";
                    }
                    catch (Exception x)
                    {
                        ViewBag.ErrorMessage = x.Message;
                    }
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Ошибочный запрос!";
            }

            FillUsers();

            return View(message);
        }


        [HttpGet]
        public IActionResult Messages()
        {
            List<Message> messages = new List<Message>();

            using (ABCTestDBConext db = new ABCTestDBConext())
            {
                int CurrentUserId = ViewBag.CurrentUser.Id;

                messages = db.Messages
                    .Where(e => e.UserID == CurrentUserId)
                    .Include(e => e.Author)
                    .ToList();

            }

            return View(messages);

        }


        private void FillUsers()
        {
            List<User> users = new List<User>();

            using (ABCTestDBConext dbctx = new ABCTestDBConext())
            {
                users.AddRange(dbctx.Users);
            }

            ViewBag.Users = new SelectList(users, "Id", "Name");
        }
    }
}

ABCSolutionsTest/Views/Home/Index.cshtml
@using ABCSolutionsTest.Helpers
@{
    Layout = "_Layout";
    ViewData["Title"] = "Стартовая страница";
}

<div class="row">
    <div class="col-md-5">
@if (ViewBag.IsAuthenticated)
{
@if (ViewBag.CurrentUser.IsAdmin)
{
        <h4>
            Административная панель
        </h4>
        <ul>
            <li><a asp-area="" asp-controller="Admin" asp-action="Create">Создать нового пользователя</a></li>
            <li><a asp-area="" asp-controller="Admin" asp-action="Users">Перейти к списку пользователей</a></li>
        </ul>
}
        <h4>
            Пользовательская панель
        </h4>
        <ul>
            <li><a asp-area="" asp-controller="User" asp-action="CreateMessage">Написать сообщение пользователю</a></li>
            <li><a asp-area="" asp-controller="User" asp-action="Messages">Перейти к списку сообщений</a></li>
        </ul>
}
else
{
        <ul>
            <li>Выполните <a asp-area="" asp-controller="Home" asp-action="Login">Login</a></li>
            <li>или <a asp-area="" asp-controller="Home" asp-action="Register">Register</a></li>
        </ul>
        <br />
        <p> Можно зайти как <strong>adm</strong> с паролем <strong>1</strong></p>
        <p> или как <strong>guest</strong> с паролем <strong>1</strong></p>
}
    </div>
</div>

ABCSolutionsTest/Views/Home/Login.cshtml
@model ABCSolutionsTest.Models.LoginModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Авторизация пользователя";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            @if (!String.IsNullOrEmpty(ViewBag.ErrorMessage))
            {
                <div class="alert alert-danger">
                    <strong>Error! </strong>@ViewBag.ErrorMessage
                </div>
            }

            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

ABCSolutionsTest/Views/Home/Register.cshtml
@model ABCSolutionsTest.Models.User
@{
    Layout = "_Layout";
    ViewData["Title"] = "Регистрация пользователя";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EMail" class="control-label"></label>
                <input asp-for="EMail" class="form-control" />
                <span asp-validation-for="EMail" class="text-danger"></span>
            </div>

            @if (!String.IsNullOrEmpty(ViewBag.ErrorMessage))
            {
            <div class="alert alert-danger">
                <strong>Error! </strong>@ViewBag.ErrorMessage
            </div>
            }

            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
        </form>

    </div>
</div>